# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

syntax_highlighter_opts:
  css_class: 'highlight'
  span:
    line_numbers: true
  block:
    line_numbers: true
    start_line: 1

# Permalinks
permalink:        pretty

# Setup
title:  wumulu
tagline:             "ML practitioner"
url:              https://nomadcube.github.io

author:
  name:           'wumengling'
  url:            https://nomadcube.github.io

paginate:         2

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon

gems: [jekyll-paginate]

